#!/bin/sh

. ./template

type "left-meta r"
type "h t t p s"
type "left-shift ;"
type "/ / w w w . y o u t u b e . c o m / w a t c h"
type "left-shift /"
type "v = d"
type "left-shift q"
type "w 4 w 9"
type "left-shift w"
type "g"
type "left-shift x"
type "c"
type "left-shift q enter"
